api/urls.py
from django.urls import path
from .views import createNote, getNote, getNotes, getRoutes, getSummary, lastNote, lastSummary, getSummaries

urlpatterns = [
    path('', getRoutes, name="getRoutes"),
    path('getnotes/', getNotes, name="getNotes"),
    path('getsummaries/', getSummaries, name="getSummaries"),
    path('lastnote/', lastNote, name="lastNote"),
    path('lastsummary/', lastSummary, name="lastSummary"),
    path('getnote/<str:pk>', getNote, name="getNote"),
    path('getsummary/<str:pk>', getSummary, name="getSummary"),
    path('createnote/', createNote, name="createNote"),
    # path('test/<str:pk>', test, name="test"),
]

docs/urls.py
from django.contrib import admin
from django.urls import path, include
from frontend.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('api/', include('api.urls')),
    path('demo/', include(('frontend.urls', 'frontend'), namespace='frontend')),
]

frontend/urls.py
from django.urls import path
from .views import formview, pdfview

urlpatterns = [
    path('', formview, name="formview"),
    path('pdf/', pdfview, name="pdfview"),
]

api/models.py
from django.db import models


class Note(models.Model):
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.body[:20]

class Summary(models.Model):
    associated_note = models.OneToOneField(Note, on_delete=models.CASCADE, blank=True, null=True)
    summary = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.associated_note.body[:20]

frontend/models.py
from django.db import models

# Create your models here.

frontend/forms.py
from django import forms
from django.db import models
from django.db.models import fields
from django.forms import ModelForm
from api.models import Note

class NoteForm(ModelForm):
    class Meta:
        model = Note
        fields = '__all__'

        # widget = {
        #     'body': forms.TextInput(attrs={'class'})
        # }

api/views.py
from django.http import response
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.serializers import Serializer
from .serializers import NoteSerializer, SummarySerializer
from .models import Note, Summary
from .nlp import sentences


@api_view(['GET'])
def getRoutes(request):
    routes = [
        {
            'Endpoint': '/getnotes/',
            'method': ["GET"],
            'body': None,
            'description': 'Returns all notes in the database'
        },
        {
            'Endpoint': '/getnote/id',
            'method': ["GET"],
            'body': None,
            'description': 'Returns the note associated with the id'
        }
        ]

    return Response(routes)

# get all
@api_view(['GET'])
def getNotes(request):
    notes = Note.objects.all()
    serializer = NoteSerializer(notes, many=True)
    return Response(serializer.data)

@api_view(['GET'])
def getSummaries(request):
    summary = Summary.objects.all()
    serializer = SummarySerializer(summary, many=True)
    return Response(serializer.data)

# get last
@api_view(['GET'])
def lastNote(request):
    last_note = Note.objects.latest('created')
    serializer = NoteSerializer(last_note, many=False)
    return Response(serializer.data)

@api_view(['GET'])
def lastSummary(request):
    last_note = Note.objects.latest('created')
    last_summary = last_note.summary
    serializer = SummarySerializer(last_summary, many=False)
    return Response(serializer.data)

# get specific
@api_view(['GET'])
def getNote(request, pk):
    note = Note.objects.get(id=pk)
    serializer = NoteSerializer(note, many=False)
    return Response(serializer.data)

@api_view(['GET'])
def getSummary(request, pk):
    note = Note.objects.get(id=pk)
    summary = note.summary
    serializer = SummarySerializer(summary, many=False)
    return Response(serializer.data)

# create
@api_view(['POST'])
def createNote(request):
    data = request.data
    note = Note.objects.create(body=data['body'])
    summary = note.summary
    serializer = SummarySerializer(summary, many=False)
    return Response(serializer.data)

# @api_view(['GET'])
# def test(request, pk):
#     note = Note.objects.get(id=pk)
#     sent = sentences(note=note.body)
#     return Response(note.body)

frontend/views.py
from django import forms
from django.shortcuts import render, HttpResponse
from .forms import NoteForm
from api.models import Note
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa


def index(request):
    return render(request, 'frontend/index.html')

def formview(request):
    form = NoteForm()

    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            note = form.save()
            summary = note.summary
            context = {'note': note.body, 'summary': summary.summary}
            return render(request, 'frontend/summary.html', context=context)

    context = {'form': form}
    return render(request, 'frontend/forms.html', context=context)

def pdfview(request):
    note = Note.objects.latest('created')
    summary = note.summary
    template_path = 'frontend/pdf.html'
    context = {'note': note.body, 'summary': summary.summary}
    response = HttpResponse(content_type='application/pdf')
    # fro download
    # response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    # for display
    response['Content-Disposition'] = 'filename="report.pdf"'
    template = get_template(template_path)
    html = template.render(context)

    pisa_status = pisa.CreatePDF(html, dest=response)
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

frontend/templates/frontend/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Notes</title>
</head>
<body style="background: #EDB906;">

<div class="container">
    {% block content %}
    {% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>   
</body>
</html>

frontend/templates/frontend/forms.html
{% extends 'frontend/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<section>
<div class="text-center"><h3>Paste Text to Summarize</h3></div>
<div class="text-center"><h6>(more than 150 words for best results)</h6></div>
<div class="row">
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
</form>
</div>
</section>

<section>

</section>
{% endblock %}

frontend/templates/frontend/index.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Arush's Notes Summarizer</title>
    <link rel="stylesheet" href={% static 'frontend/bootstrap/css/bootstrap.min.css' %}>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css">
    <link rel="stylesheet" href={% static 'frontend/css/Navigation-Clean.css' %}>
</head>

<body id="page-top">
    <nav class="navbar navbar-light navbar-expand-md navigation-clean">
        <div class="container"><a class="navbar-brand" data-bss-hover-animate="swing" href="https://arushsharma.tech/">Arush Sharma</a><button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-1"><span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item"><a class="nav-link" data-bss-hover-animate="tada" href="https://github.com/rushmash91/Notes-Summarizer">Project Github Repo</a></li>
                    <li class="nav-item"><a class="nav-link" data-bss-hover-animate="tada" href="https://arushsharma.tech/">Connect with me</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <header class="d-flex masthead" data-aos="fade" style="background: var(--bs-secondary);">
        <div class="container my-auto text-center">
            <h1 class="jello animated mb-1">Notes Summarizer</h1>
            <h3 class="mb-5"><em class="tada animated">A tool to extract meaningful data from the clutter..</em></h3><a class="btn btn-primary shake animated btn-xl js-scroll-trigger" role="button" href="/demo">Try it!</a>
            <div class="overlay"></div>
        </div>
    </header>
    <section id="about" class="content-section bg-light">
        <div class="container text-center">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <h2 data-aos="zoom-in">Ranking sentences based on their contextual importance!</h2>
                    <p data-aos="zoom-in" class="lead mb-5">Take a look at the project code&nbsp;<span>&nbsp;</span><a href="https://github.com/rushmash91/Notes-Summarizer">HERE</a><span>!</span></p>
                </div>
            </div>
        </div>
    </section>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src={% static 'frontend/js/bs-init.js' %}></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>
    <script src={% static 'frontend/js/stylish-portfolio.js' %}></script>
</body>

</html>

frontend/templates/frontend/pdf.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>PDF Report</title>
   
</head>
<body>
<div class="container">
    <div class="row text-center"><h2>Notes Summarizer by arushsharma.tech</h2></div>
    <div class="row"><h2>Summary</h2></div>
    <div class="row">{{ summary }}</div>
    <div class="row"><h2>Note</h2></div>
    <div class="row">{{ note }}</div>
</div>

</body>
</html>

frontend/templates/frontend/summary.html
{% extends 'frontend/base.html' %}

{% block content %}
    <h3>Summary</h3>
    <div> {{ summary }} </div>
    <h3>Note</h3>
    <div> {{ note }} </div>
    <div><a class="btn btn-primary" href="{% url 'frontend:pdfview' %}">Download A PDF</a></div>
{% endblock %}